version: '3'

services:
    front:
        build:
            context: ../build/app.front/
            dockerfile: docker/development.dockerfile
        expose:
            - 3001
        ports:
            - 3001:3001
        depends_on:
            - db
            - ssr.cache
        restart: on-failure
        volumes:
            - ../build/app.front/build/app.front.client/:/usr/src/app/client/
            - ../build/app.front/build/app.front.server/:/usr/src/app/server/
        environment:
            - PORT=3001
            - AUTH__ENABLED=1
            - URL__ROOT=http://localhost:3001/
            - url.root=http://localhost:3001/
            - url.auth.outer=http://localhost:3200/
            - url.auth.inner=http://auth:3200/
            - URL__API=http://localhost:3100
            - URL__API_SSR=http://api:3100
            - FOLDER__ROOT=/usr/src/app/
            - FOLDER__PUBLIC=/usr/src/app/client/public/
            - FOLDER__TEMPLATE=/usr/src/app/client/html/
            - FILE__TEMPLATE__ASSETS=/usr/src/app/client/assets.html
            - PROJECT__NAME=Eisenwerk
            - SSR__CACHE__URL=redis://ssr.cache:6379
            - auth.oauth2.google.client-id=1075582803417-vnra2i2mg3g1j6na4h2il2h219qoh4ah.apps.googleusercontent.com
            - auth.oauth2.google.secret=uAiRXseKeV_kGyqeUsIAHeu8

    api:
        build:
            context: ../build/app.api/
            dockerfile: docker/development.dockerfile
        expose:
            - 3100
        ports:
            - 3100:3100
        depends_on:
            - db
        restart: on-failure
        environment:
            - PORT=3100
            - URL__ROOT=http://localhost:3100/
            - URL__DB=mongodb://db:27017/ew
            - CORS__ORIGIN=http://localhost:3000,http://localhost:3010,http://localhost:3001
            - auth.secret=P4cRdF5mzSMPvy4hCdpKCjHMp3vZ4UvynaxhEAJK

    auth:
        build:
            context: ../build/app.auth/
            dockerfile: docker/development.dockerfile
        expose:
            - 3200
        ports:
            - 3200:3200
        depends_on:
            - db
        restart: on-failure
        environment:
            - PORT=3200
            - URL__ROOT=http://localhost:3100/
            - URL__DB=mongodb://db:27017/ew
            - CORS__ORIGIN=http://localhost:3000,http://localhost:3001
            - AUTH__SECRET=P4cRdF5mzSMPvy4hCdpKCjHMp3vZ4UvynaxhEAJK
            - AUTH__LOCAL__ENABLED=1
            - AUTH__GOOGLE__CLIENT_ID=745832723828-5o4p8djtufdg3dbt7vq49jicgtf576nv.apps.googleusercontent.com
            - AUTH__GOOGLE__SECRET=DC_XrNDl5SkVgDQOOq-0L6Zg
            - AUTH__GOOGLE__DOMAIN=
            - auth.jwt.ttl=7d
            - auth.secret=P4cRdF5mzSMPvy4hCdpKCjHMp3vZ4UvynaxhEAJK

    ssr.cache:
        build:
            context: ../app.ssr.cache/
            dockerfile: development.dockerfile
        expose:
            - 6379
        ports:
            - 6379:6379

    db:
        image: 'mongo:latest'
        restart: always
        ports:
            - 3900:27017

    front.browser-sync:
        image: ustwo/browser-sync
        command: start --proxy "front:3001" --port 3000 --files "/source" --no-notify
        volumes:
            - ../build/app.front/build/app.front.client/public/:/source
        expose:
            - 3000
        ports:
            - '3000:3000'
