import EnumFactory from '../util/enum-factory/index.js';

class LanguageEnumFactory extends EnumFactory {
    constructor(items) {
        super(items || [
            {key: 'AF', valueDE: 'Afrikaans', value: 'Afrikaans'},
            {key: 'SQ', valueDE: 'Albanisch', value: 'Albanian'},
            {key: 'AM', valueDE: 'Amharisch', value: 'Amharic'},
            {key: 'AR', valueDE: 'Arabisch', value: 'Arabic'},
            {key: 'HY', valueDE: 'Armenisch', value: 'Armenian'},
            {key: 'AZ', valueDE: 'Aserbaidschanisch', value: 'Azerbaijani'},
            {key: 'EU', valueDE: 'Baskisch', value: 'Basque'},
            {key: 'BN', valueDE: 'Bengalisch', value: 'Bengali'},
            {key: 'BT', valueDE: 'Bhutanisch', value: 'Bhutanese'},
            {key: 'MY', valueDE: 'Birmanisch', value: 'Burmese'},
            {key: 'BI', valueDE: 'Bislama', value: 'Bislama'},
            {key: 'BS', valueDE: 'Bosnisch', value: 'Bosnian'},
            {key: 'BG', valueDE: 'Bulgarisch', value: 'Bulgarian'},
            {key: 'ZH', valueDE: 'Chinesisch', value: 'Chinese'},
            {key: 'PR', valueDE: 'Dari', value: 'Dari'},
            {key: 'DE', valueDE: 'Deutsch', value: 'German'},
            {key: 'DA', valueDE: 'Dänisch', value: 'Danish'},
            {key: 'EN', valueDE: 'Englisch', value: 'English'},
            {key: 'EO', valueDE: 'Esperanto', value: 'Esperanto'},
            {key: 'ET', valueDE: 'Estnisch', value: 'Estonian'},
            {key: 'FJ', valueDE: 'Fidschianisch', value: 'Fijian'},
            {key: 'FT', valueDE: 'Filipino (Tagalog)', value: 'Filipino'},
            {key: 'FI', valueDE: 'Finnisch', value: 'Finnish'},
            {key: 'FR', valueDE: 'Französisch', value: 'French'},
            {key: 'GL', valueDE: 'Galicisch', value: 'Galician'},
            {key: 'KA', valueDE: 'Georgisch', value: 'Georgian'},
            {key: 'GI', valueDE: 'Gilbertesisch (Kiribatisch)', value: 'Gilbertese'},
            {key: 'EL', valueDE: 'Griechisch', value: 'Georgian'},
            {key: 'GU', valueDE: 'Gujarati', value: 'Gujarati'},
            {key: 'HE', valueDE: 'Hebräisch', value: 'Hebrew'},
            {key: 'HI', valueDE: 'Hindi', value: 'Hindi'},
            {key: 'ID', valueDE: 'Indonesisch', value: 'Indonesian'},
            {key: 'GA', valueDE: 'Irisch', value: 'Irish'},
            {key: 'IS', valueDE: 'Isländisch', value: 'Icelandic'},
            {key: 'IT', valueDE: 'Italienisch', value: 'Italian'},
            {key: 'JA', valueDE: 'Japanisch', value: 'Japanese'},
            {key: 'KM', valueDE: 'Kambodschanisch', value: 'Cambodian'},
            {key: 'KN', valueDE: 'Kannada', value: 'Kannada'},
            {key: 'KK', valueDE: 'Kasachisch', value: 'Kazakh'},
            {key: 'CA', valueDE: 'Katalanisch', value: 'Catalan'},
            {key: 'KY', valueDE: 'Kirgisisch', value: 'Kyrgyz'},
            {key: 'RN', valueDE: 'Kirundi', value: 'Kirundi'},
            {key: 'KO', valueDE: 'Koreanisch (Demokratische Volksrepublik Korea)', value: 'Korean (Democratic People\'s Republic of Korea)'},
            {key: 'KS', valueDE: 'Koreanisch (Republik Korea)', value: 'Korean (Republic of Korea)'},
            {key: 'HR', valueDE: 'Kroatisch', value: 'Croatian'},
            {key: 'KU', valueDE: 'Kurdisch', value: 'Kurdish'},
            {key: 'LO', valueDE: 'Laotisch', value: 'Lao'},
            {key: 'LA', valueDE: 'Lateinisch', value: 'Latin'},
            {key: 'LV', valueDE: 'Lettisch', value: 'Latvian'},
            {key: 'LB', valueDE: 'Letzeburgisch', value: 'Luxembourgish'},
            {key: 'LT', valueDE: 'Litauisch', value: 'Lithuanian'},
            {key: 'MG', valueDE: 'Madagassisch', value: 'Malagasy'},
            {key: 'ML', valueDE: 'Malaiisch', value: 'Malay'},
            {key: 'ML', valueDE: 'Malajalam', value: 'Malayalam'},
            {key: 'DV', valueDE: 'Maledivisch', value: 'Maldivian'},
            {key: 'MT', valueDE: 'Maltesisch', value: 'Maltese'},
            {key: 'MR', valueDE: 'Marathi', value: 'Marathi'},
            {key: 'MK', valueDE: 'Mazedonisch', value: 'Macedonian'},
            {key: 'MN', valueDE: 'Mongolisch', value: 'Mongolian'},
            {key: 'MI', valueDE: 'Mongolisch (Innere Mongolei, China)', value: 'Mongolian'},
            {key: 'CN', valueDE: 'Montenegrinisch', value: 'Montenegrin'},
            {key: 'NB', valueDE: 'Ndebele', value: 'Ndebele'},
            {key: 'NE', valueDE: 'Nepalesisch', value: 'Nepalese'},
            {key: 'TP', valueDE: 'Neumelanesisch (Pidgin)', value: 'Neo-Melanesian'},
            {key: 'NL', valueDE: 'Niederländisch', value: 'Dutch'},
            {key: 'NS', valueDE: 'Nordsotho', value: 'Northern Sotho'},
            {key: 'NO', valueDE: 'Norwegisch', value: 'Norwegian'},
            {key: 'PW', valueDE: 'Palauisch', value: 'Palauan'},
            {key: 'PS', valueDE: 'Paschtu', value: 'Pashto'},
            {key: 'FA', valueDE: 'Persisch', value: 'Persian'},
            {key: 'PL', valueDE: 'Polnisch', value: 'Polish'},
            {key: 'PT', valueDE: 'Portugiesisch', value: 'Portuguese'},
            {key: 'RW', valueDE: 'Ruandisch', value: 'Rwandan'},
            {key: 'RO', valueDE: 'Rumänisch', value: 'Romanian'},
            {key: 'RU', valueDE: 'Russisch', value: 'Russian'},
            {key: 'RM', valueDE: 'Rätoromanisch', value: 'Rhaeto-Romanic'},
            {key: 'SM', valueDE: 'Samoanisch', value: 'Samoan'},
            {key: 'SV', valueDE: 'Schwedisch', value: 'Swedish'},
            {key: 'SR', valueDE: 'Serbisch', value: 'Serbian'},
            {key: 'SI', valueDE: 'Singhalesisch', value: 'Sinhalese'},
            {key: 'SK', valueDE: 'Slowakisch', value: 'Slovak'},
            {key: 'SL', valueDE: 'Slowenisch', value: 'Slovenian'},
            {key: 'SO', valueDE: 'Somali', value: 'Somali'},
            {key: 'ES', valueDE: 'Spanisch', value: 'Spanish'},
            {key: 'SW', valueDE: 'Suaheli', value: 'Swahili'},
            {key: 'SZ', valueDE: 'Swasi', value: 'Swazi'},
            {key: 'SU', valueDE: 'Südsotho', value: 'Southern Sotho'},
            {key: 'TG', valueDE: 'Tadschikisch', value: 'Tajik'},
            {key: 'TA', valueDE: 'Tamilisch', value: 'Tamil'},
            {key: 'TE', valueDE: 'Telugu', value: 'Telugu'},
            {key: 'TH', valueDE: 'Thailändisch', value: 'Thai'},
            {key: 'TT', valueDE: 'Tibetisch', value: 'Tibetan'},
            {key: 'TI', valueDE: 'Tigrinja', value: 'Tigrinja'},
            {key: 'TO', valueDE: 'Tongaisch', value: 'Tongan'},
            {key: 'CS', valueDE: 'Tschechisch', value: 'Czech'},
            {key: 'TN', valueDE: 'Tsonga', value: 'Tsonga'},
            {key: 'TB', valueDE: 'Tsuana (Botsuana)', value: 'Tsuana (Botswana)'},
            {key: 'TS', valueDE: 'Tsuana (Südafrika)', value: 'Tsuana (South Africa)'},
            {key: 'TK', valueDE: 'Turkmenisch', value: 'Turkmen'},
            {key: 'TU', valueDE: 'Tuvalu(isch)', value: 'Tuvaluan'},
            {key: 'TR', valueDE: 'Türkisch', value: 'Turkish'},
            {key: 'UG', valueDE: 'Uighurisch', value: 'Uyghur'},
            {key: 'UK', valueDE: 'Ukrainisch', value: 'Ukrainian'},
            {key: 'HU', valueDE: 'Ungarisch', value: 'Hungarian'},
            {key: 'UR', valueDE: 'Urdu', value: 'Urdu'},
            {key: 'UZ', valueDE: 'Usbekisch', value: 'Uzbek'},
            {key: 'VE', valueDE: 'Venda', value: 'Venda'},
            {key: 'VI', valueDE: 'Vietnamesisch', value: 'Vietnamese'},
            {key: 'WE', valueDE: 'Weißrussisch', value: 'Belarusian'},
            {key: 'XH', valueDE: 'Xhosa', value: 'Xhosa'},
            {key: 'ZU', valueDE: 'Zulu', value: 'Zulu'}
        ]);
    }
}

export default new LanguageEnumFactory();
