import EnumFactory from '../../../lib/util/enum-factory/index.js';

class CountryEnumFactory extends EnumFactory {
    constructor(items) {
        super(items || [
            { key: 'AD', value: 'Andorra', valueDE: 'Andorra', },
            { key: 'AE', value: 'United Arab Emirates', valueDE: 'Vereinte Arabische Emirate', },
            { key: 'AF', value: 'Afghanistan', valueDE: 'Afghanistan', },
            { key: 'AG', value: 'Antigua and Barbuda', valueDE: 'Antigua und Barbuda', },
            { key: 'AI', value: 'Anguilla', valueDE: '', },
            { key: 'AL', value: 'Albania', valueDE: 'Albanien', },
            { key: 'AM', value: 'Armenia', valueDE: 'Armenien', },
            { key: 'AO', value: 'Angola', valueDE: 'Angola', },
            { key: 'AQ', value: 'Antarctica', valueDE: '', },
            { key: 'AR', value: 'Argentina', valueDE: 'Argentinien', },
            { key: 'AS', value: 'American Samoa', valueDE: '', },
            { key: 'AT', value: 'Austria', valueDE: 'Österreich', },
            { key: 'AU', value: 'Australia', valueDE: 'Australien', },
            { key: 'AW', value: 'Aruba', valueDE: '', },
            { key: 'AX', value: 'Aland Islands', valueDE: '', },
            { key: 'AZ', value: 'Azerbaijan', valueDE: 'Aserbaidschan', },
            { key: 'BA', value: 'Bosnia and Herzegovina', valueDE: 'Bosnien und Herzegowina', },
            { key: 'BB', value: 'Barbados', valueDE: 'Barbados', },
            { key: 'BD', value: 'Bangladesh', valueDE: 'Bangladesch', },
            { key: 'BE', value: 'Belgium', valueDE: 'Belgien', },
            { key: 'BF', value: 'Burkina Faso', valueDE: 'Burkina Faso', },
            { key: 'BG', value: 'Bulgaria', valueDE: 'Bulgarien', },
            { key: 'BH', value: 'Bahrain', valueDE: 'Bahrain', },
            { key: 'BI', value: 'Burundi', valueDE: 'Burundi', },
            { key: 'BJ', value: 'Benin', valueDE: 'Benin', },
            { key: 'BL', value: 'Saint Barthelemy', valueDE: '', },
            { key: 'BM', value: 'Bermuda', valueDE: '', },
            { key: 'BN', value: 'Brunei', valueDE: 'Brunei', },
            { key: 'BO', value: 'Bolivia', valueDE: 'Bolivien', },
            { key: 'BQ', value: 'Bonaire, Saint Eustatius and Saba ', valueDE: '', },
            { key: 'BR', value: 'Brazil', valueDE: 'Brasilien', },
            { key: 'BS', value: 'Bahamas', valueDE: 'Bahamas', },
            { key: 'BT', value: 'Bhutan', valueDE: 'Bhutan', },
            { key: 'BV', value: 'Bouvet Island', valueDE: '', },
            { key: 'BW', value: 'Botswana', valueDE: 'Botswana', },
            { key: 'BY', value: 'Belarus', valueDE: 'Weißrussland', },
            { key: 'BZ', value: 'Belize', valueDE: 'Belize', },
            { key: 'CA', value: 'Canada', valueDE: 'Kanada', },
            { key: 'CC', value: 'Cocos Islands', valueDE: '', },
            { key: 'CD', value: 'Democratic Republic of the Congo', valueDE: '', },
            { key: 'CF', value: 'Central African Republic', valueDE: 'Zentralafrikanische Republik', },
            { key: 'CG', value: 'Republic of the Congo', valueDE: 'Republik Kongo', },
            { key: 'CH', value: 'Switzerland', valueDE: 'Schweiz', },
            { key: 'CI', value: 'Ivory Coast', valueDE: 'Elfenbeinküste', },
            { key: 'CK', value: 'Cook Islands', valueDE: '', },
            { key: 'CL', value: 'Chile', valueDE: 'Chile', },
            { key: 'CM', value: 'Cameroon', valueDE: 'Kamerun', },
            { key: 'CN', value: 'China', valueDE: 'China', },
            { key: 'CO', value: 'Colombia', valueDE: 'Kolumbien', },
            { key: 'CR', value: 'Costa Rica', valueDE: 'Costa Rica', },
            { key: 'CU', value: 'Cuba', valueDE: 'Kuba', },
            { key: 'CV', value: 'Cape Verde', valueDE: 'Kap Verde', },
            { key: 'CW', value: 'Curacao', valueDE: '', },
            { key: 'CX', value: 'Christmas Island', valueDE: '', },
            { key: 'CY', value: 'Cyprus', valueDE: 'Zypern', },
            { key: 'CZ', value: 'Czechia', valueDE: 'Tschechische Republik', },
            { key: 'DE', value: 'Germany', valueDE: 'Deutschland', },
            { key: 'DJ', value: 'Djibouti', valueDE: 'Dschibuti', },
            { key: 'DK', value: 'Denmark', valueDE: 'Dänemark', },
            { key: 'DM', value: 'Dominica', valueDE: 'Dominica', },
            { key: 'DO', value: 'Dominican Republic', valueDE: 'Dominikanische Republik', },
            { key: 'DZ', value: 'Algeria', valueDE: 'Algerien', },
            { key: 'EC', value: 'Ecuador', valueDE: 'Ecuador', },
            { key: 'EE', value: 'Estonia', valueDE: 'Estland', },
            { key: 'EG', value: 'Egypt', valueDE: 'Ägypten', },
            { key: 'EH', value: 'Western Sahara', valueDE: '', },
            { key: 'ER', value: 'Eritrea', valueDE: 'Eritrea', },
            { key: 'ES', value: 'Spain', valueDE: 'Spanien', },
            { key: 'ET', value: 'Ethiopia', valueDE: 'Äthiopien', },
            { key: 'FI', value: 'Finland', valueDE: 'Finnland', },
            { key: 'FJ', value: 'Fiji', valueDE: 'Fidschi', },
            { key: 'FK', value: 'Falkland Islands', valueDE: '', },
            { key: 'FM', value: 'Micronesia', valueDE: 'Mikronesien', },
            { key: 'FO', value: 'Faroe Islands', valueDE: '', },
            { key: 'FR', value: 'France', valueDE: 'Frankreich', },
            { key: 'GA', value: 'Gabon', valueDE: 'Gabun', },
            { key: 'GB', value: 'United Kingdom', valueDE: 'Großbritannien', },
            { key: 'GD', value: 'Grenada', valueDE: 'Grenada', },
            { key: 'GE', value: 'Georgia', valueDE: 'Georgien', },
            { key: 'GF', value: 'French Guiana', valueDE: '', },
            { key: 'GG', value: 'Guernsey', valueDE: '', },
            { key: 'GH', value: 'Ghana', valueDE: 'Ghana', },
            { key: 'GI', value: 'Gibraltar', valueDE: '', },
            { key: 'GL', value: 'Greenland', valueDE: '', },
            { key: 'GM', value: 'Gambia', valueDE: 'Gambia', },
            { key: 'GN', value: 'Guinea', valueDE: 'Guinea', },
            { key: 'GP', value: 'Guadeloupe', valueDE: '', },
            { key: 'GQ', value: 'Equatorial Guinea', valueDE: 'Äquatorialguinea', },
            { key: 'GR', value: 'Greece', valueDE: 'Griechenland', },
            { key: 'GS', value: 'South Georgia and the South Sandwich Islands', valueDE: '', },
            { key: 'GT', value: 'Guatemala', valueDE: 'Guatemala', },
            { key: 'GU', value: 'Guam', valueDE: '', },
            { key: 'GW', value: 'Guinea-Bissau', valueDE: 'Guinea-Bissau', },
            { key: 'GY', value: 'Guyana', valueDE: 'Guyana', },
            { key: 'HK', value: 'Hong Kong', valueDE: '', },
            { key: 'HM', value: 'Heard Island and McDonald Islands', valueDE: '', },
            { key: 'HN', value: 'Honduras', valueDE: 'Honduras', },
            { key: 'HR', value: 'Croatia', valueDE: 'Kroatien', },
            { key: 'HT', value: 'Haiti', valueDE: 'Haiti', },
            { key: 'HU', value: 'Hungary', valueDE: 'Ungarn', },
            { key: 'ID', value: 'Indonesia', valueDE: 'Indonesien', },
            { key: 'IE', value: 'Ireland', valueDE: 'Irland', },
            { key: 'IL', value: 'Israel', valueDE: 'Israel', },
            { key: 'IM', value: 'Isle of Man', valueDE: '', },
            { key: 'IN', value: 'India', valueDE: 'Indien', },
            { key: 'IO', value: 'British Indian Ocean Territory', valueDE: '', },
            { key: 'IQ', value: 'Iraq', valueDE: 'Irak', },
            { key: 'IR', value: 'Iran', valueDE: 'Iran', },
            { key: 'IS', value: 'Iceland', valueDE: 'Island', },
            { key: 'IT', value: 'Italy', valueDE: 'Italien', },
            { key: 'JE', value: 'Jersey', valueDE: '', },
            { key: 'JM', value: 'Jamaica', valueDE: 'Jamaika', },
            { key: 'JO', value: 'Jordan', valueDE: 'Jordanien', },
            { key: 'JP', value: 'Japan', valueDE: 'Japan', },
            { key: 'KE', value: 'Kenya', valueDE: 'Kenia', },
            { key: 'KG', value: 'Kyrgyzstan', valueDE: 'Kirgisistan', },
            { key: 'KH', value: 'Cambodia', valueDE: 'Kambodscha', },
            { key: 'KI', value: 'Kiribati', valueDE: 'Kiribati', },
            { key: 'KM', value: 'Comoros', valueDE: 'Komoren', },
            { key: 'KN', value: 'Saint Kitts and Nevis', valueDE: 'St. Kitts und Nevis', },
            { key: 'KP', value: 'North Korea', valueDE: 'Nordkorea', },
            { key: 'KR', value: 'South Korea', valueDE: 'Südkorea', },
            { key: 'XK', value: 'Kosovo', valueDE: '', },
            { key: 'KW', value: 'Kuwait', valueDE: 'Kuwait', },
            { key: 'KY', value: 'Cayman Islands', valueDE: '', },
            { key: 'KZ', value: 'Kazakhstan', valueDE: 'Kasachstan', },
            { key: 'LA', value: 'Laos', valueDE: 'Laos', },
            { key: 'LB', value: 'Lebanon', valueDE: 'Libanon', },
            { key: 'LC', value: 'Saint Lucia', valueDE: 'St. Lucia', },
            { key: 'LI', value: 'Liechtenstein', valueDE: 'Liechtenstein', },
            { key: 'LK', value: 'Sri Lanka', valueDE: 'Sri Lanka', },
            { key: 'LR', value: 'Liberia', valueDE: 'Liberia', },
            { key: 'LS', value: 'Lesotho', valueDE: 'Lesotho', },
            { key: 'LT', value: 'Lithuania', valueDE: 'Litauen', },
            { key: 'LU', value: 'Luxembourg', valueDE: 'Luxemburg', },
            { key: 'LV', value: 'Latvia', valueDE: 'Lettland', },
            { key: 'LY', value: 'Libya', valueDE: 'Libyen', },
            { key: 'MA', value: 'Morocco', valueDE: 'Marokko', },
            { key: 'MC', value: 'Monaco', valueDE: 'Monaco', },
            { key: 'MD', value: 'Moldova', valueDE: 'Moldawien', },
            { key: 'ME', value: 'Montenegro', valueDE: 'Montenegro', },
            { key: 'MF', value: 'Saint Martin', valueDE: '', },
            { key: 'MG', value: 'Madagascar', valueDE: 'Madagaskar', },
            { key: 'MH', value: 'Marshall Islands', valueDE: 'Marshallinseln', },
            { key: 'MK', value: 'Macedonia', valueDE: 'Mazedonien', },
            { key: 'ML', value: 'Mali', valueDE: 'Mali', },
            { key: 'MM', value: 'Myanmar', valueDE: 'Myanmar', },
            { key: 'MN', value: 'Mongolia', valueDE: 'Mongolei', },
            { key: 'MO', value: 'Macao', valueDE: '', },
            { key: 'MP', value: 'Northern Mariana Islands', valueDE: '', },
            { key: 'MQ', value: 'Martinique', valueDE: '', },
            { key: 'MR', value: 'Mauritania', valueDE: 'Mauretanien', },
            { key: 'MS', value: 'Montserrat', valueDE: '', },
            { key: 'MT', value: 'Malta', valueDE: 'Malta', },
            { key: 'MU', value: 'Mauritius', valueDE: 'Mauritius', },
            { key: 'MV', value: 'Maldives', valueDE: 'Malediven', },
            { key: 'MW', value: 'Malawi', valueDE: 'Malawi', },
            { key: 'MX', value: 'Mexico', valueDE: 'Mexiko', },
            { key: 'MY', value: 'Malaysia', valueDE: 'Malaysia', },
            { key: 'MZ', value: 'Mozambique', valueDE: 'Mosambik', },
            { key: 'NA', value: 'Namibia', valueDE: 'Namibia', },
            { key: 'NC', value: 'New Caledonia', valueDE: '', },
            { key: 'NE', value: 'Niger', valueDE: 'Niger', },
            { key: 'NF', value: 'Norfolk Island', valueDE: '', },
            { key: 'NG', value: 'Nigeria', valueDE: 'Nigeria', },
            { key: 'NI', value: 'Nicaragua', valueDE: 'Nicaragua', },
            { key: 'NL', value: 'Netherlands', valueDE: 'Niederlande', },
            { key: 'NO', value: 'Norway', valueDE: 'Norwegen', },
            { key: 'NP', value: 'Nepal', valueDE: 'Nepal', },
            { key: 'NR', value: 'Nauru', valueDE: 'Nauru', },
            { key: 'NU', value: 'Niue', valueDE: '', },
            { key: 'NZ', value: 'New Zealand', valueDE: 'Neuseeland', },
            { key: 'OM', value: 'Oman', valueDE: 'Oman', },
            { key: 'PA', value: 'Panama', valueDE: 'Panama', },
            { key: 'PE', value: 'Peru', valueDE: 'Peru', },
            { key: 'PF', value: 'French Polynesia', valueDE: '', },
            { key: 'PG', value: 'Papua New Guinea', valueDE: 'Papua-Neuguinea', },
            { key: 'PH', value: 'Philippines', valueDE: 'Philippinen', },
            { key: 'PK', value: 'Pakistan', valueDE: 'Pakistan', },
            { key: 'PL', value: 'Poland', valueDE: 'Polen', },
            { key: 'PM', value: 'Saint Pierre and Miquelon', valueDE: '', },
            { key: 'PN', value: 'Pitcairn', valueDE: '', },
            { key: 'PR', value: 'Puerto Rico', valueDE: '', },
            { key: 'PS', value: 'Palestinian Territory', valueDE: '', },
            { key: 'PT', value: 'Portugal', valueDE: 'Portugal', },
            { key: 'PW', value: 'Palau', valueDE: 'Palau', },
            { key: 'PY', value: 'Paraguay', valueDE: 'Paraguay', },
            { key: 'QA', value: 'Qatar', valueDE: 'Katar', },
            { key: 'RE', value: 'Reunion', valueDE: '', },
            { key: 'RO', value: 'Romania', valueDE: 'Rumänien', },
            { key: 'RS', value: 'Serbia', valueDE: 'Serbien', },
            { key: 'RU', value: 'Russia', valueDE: 'Russland', },
            { key: 'RW', value: 'Rwanda', valueDE: 'Ruanda', },
            { key: 'SA', value: 'Saudi Arabia', valueDE: 'Saudi-Arabien', },
            { key: 'SB', value: 'Solomon Islands', valueDE: 'Salomon-Inseln', },
            { key: 'SC', value: 'Seychelles', valueDE: 'Seychellen', },
            { key: 'SD', value: 'Sudan', valueDE: 'Sudan', },
            { key: 'SS', value: 'South Sudan', valueDE: 'Südsudan', },
            { key: 'SE', value: 'Sweden', valueDE: 'Schweden', },
            { key: 'SG', value: 'Singapore', valueDE: 'Singapur', },
            { key: 'SH', value: 'Saint Helena', valueDE: '', },
            { key: 'SI', value: 'Slovenia', valueDE: 'Slowenien', },
            { key: 'SJ', value: 'Svalbard and Jan Mayen', valueDE: '', },
            { key: 'SK', value: 'Slovakia', valueDE: 'Slowakei', },
            { key: 'SL', value: 'Sierra Leone', valueDE: 'Sierra Leone', },
            { key: 'SM', value: 'San Marino', valueDE: 'San Marino', },
            { key: 'SN', value: 'Senegal', valueDE: 'Senegal', },
            { key: 'SO', value: 'Somalia', valueDE: 'Somalia', },
            { key: 'SR', value: 'Suriname', valueDE: 'Suriname', },
            { key: 'ST', value: 'Sao Tome and Principe', valueDE: 'São Tomé und Príncipe', },
            { key: 'SV', value: 'El Salvador', valueDE: 'El Salvador', },
            { key: 'SX', value: 'Sint Maarten', valueDE: '', },
            { key: 'SY', value: 'Syria', valueDE: 'Syrien', },
            { key: 'SZ', value: 'Swaziland', valueDE: 'Swasiland', },
            { key: 'TC', value: 'Turks and Caicos Islands', valueDE: '', },
            { key: 'TD', value: 'Chad', valueDE: 'Tschad', },
            { key: 'TF', value: 'French Southern Territories', valueDE: '', },
            { key: 'TG', value: 'Togo', valueDE: 'Togo', },
            { key: 'TH', value: 'Thailand', valueDE: 'Thailand', },
            { key: 'TJ', value: 'Tajikistan', valueDE: 'Tadschikistan', },
            { key: 'TK', value: 'Tokelau', valueDE: '', },
            { key: 'TL', value: 'Timor Leste', valueDE: 'Osttimor', },
            { key: 'TM', value: 'Turkmenistan', valueDE: 'Turkmenistan', },
            { key: 'TN', value: 'Tunisia', valueDE: 'Tunesien', },
            { key: 'TO', value: 'Tonga', valueDE: 'Tonga', },
            { key: 'TR', value: 'Turkey', valueDE: 'Türkei', },
            { key: 'TT', value: 'Trinidad and Tobago', valueDE: 'Trinidad und Tobago', },
            { key: 'TV', value: 'Tuvalu', valueDE: 'Tuvalu', },
            { key: 'TW', value: 'Taiwan', valueDE: '', },
            { key: 'TZ', value: 'Tanzania', valueDE: 'Tansania', },
            { key: 'UA', value: 'Ukraine', valueDE: 'Ukraine', },
            { key: 'UG', value: 'Uganda', valueDE: 'Uganda', },
            { key: 'UM', value: 'United States Minor Outlying Islands', valueDE: '', },
            { key: 'US', value: 'United States', valueDE: 'Vereinigte Staaten von Amerika', },
            { key: 'UY', value: 'Uruguay', valueDE: 'Uruguay', },
            { key: 'UZ', value: 'Uzbekistan', valueDE: 'Usbekistan', },
            { key: 'VA', value: 'Vatican', valueDE: '', },
            { key: 'VC', value: 'Saint Vincent and the Grenadines', valueDE: 'St. Vincent und die Grenadinen', },
            { key: 'VE', value: 'Venezuela', valueDE: 'Venezuela', },
            { key: 'VG', value: 'British Virgin Islands', valueDE: '', },
            { key: 'VI', value: 'U.S. Virgin Islands', valueDE: '', },
            { key: 'VN', value: 'Vietnam', valueDE: 'Vietnam', },
            { key: 'VU', value: 'Vanuatu', valueDE: 'Vanuatu', },
            { key: 'WF', value: 'Wallis and Futuna', valueDE: '', },
            { key: 'WS', value: 'Samoa', valueDE: 'Samoa', },
            { key: 'YE', value: 'Yemen', valueDE: 'Jemen', },
            { key: 'YT', value: 'Mayotte', valueDE: '', },
            { key: 'ZA', value: 'South Africa', valueDE: 'Südafrika', },
            { key: 'ZM', value: 'Zambia', valueDE: 'Sambia', },
            { key: 'ZW', value: 'Zimbabwe', valueDE: 'Simbabwe', },
            { key: 'CS', value: 'Serbia and Montenegro', valueDE: '', },
            { key: 'AN', value: 'Netherlands Antilles', valueDE: '', },
        ]);
    }
}

export default new CountryEnumFactory();
