#!/usr/bin/env node

const process = require('process');
const Project = require('docker-build-tool');

process.on('unhandledRejection', (reason, p) => {
	console.log('Unhandled Rejection at: ', p, ' reason: ', reason);
});
process.on('uncaughtException', (err) => {
	console.log('Uncaught Exception thrown ', err);
	console.dir(err.stack);
});

(new Project({
    composeFile: `${__dirname}/../docker/development.yml`,
    projectFolder: `${__dirname}/../`,
    dockerLogsPollingInterval: 1000,
    // debug: true,
})).run();
